export let ids = {
  'Anaheim Ducks': 'ANA',
  ANA: 'ANA',
  'Arizona Coyotes': 'ARI',
  ARI: 'ARI',
  'Boston Bruins': 'BOS',
  BOS: 'BOS_20082009-20222023',
  'Buffalo Sabres': 'BUF',
  BUF: 'BUF',
  'Calgary Flames': 'CGY',
  CGY: 'CGY',
  'Carolina Hurricanes': 'CAR',
  CAR: 'CAR',
  'Chicago Blackhawks': 'CHI',
  CHI: 'CHI',
  'Colorado Avalanche': 'COL',
  COL: 'COL',
  'Columbus Blue Jackets': 'CBJ',
  CBJ: 'CBJ',
  'Dallas Stars': 'DAL',
  DAL: 'DAL',
  'Detroit Red Wings': 'DET',
  DET: 'DET',
  'Edmonton Oilers': 'EDM',
  EDM: 'EDM',
  'Florida Panthers': 'FLA',
  FLA: 'FLA',
  'Los Angeles Kings': 'LAK',
  LAK: 'LAK',
  'Minnesota Wild': 'MIN',
  MIN: 'MIN',
  'Montréal Canadiens': 'MTL',
  MTL: 'MTL',
  'Nashville Predators': 'NSH',
  NSH: 'NSH',
  'New Jersey Devils': 'NJD',
  NJD: 'NJD',
  'New York Islanders': 'NYI',
  NYI: 'NYI',
  'New York Rangers': 'NYR',
  NYR: 'NYR',
  'Ottawa Senators': 'OTT',
  OTT: 'OTT',
  'Philadelphia Flyers': 'PHI',
  PHI: 'PHI_19992000-20222023',
  'Pittsburgh Penguins': 'PIT',
  PIT: 'PIT',
  'San Jose Sharks': 'SJS',
  SJS: 'SJS',
  'Seattle Kraken': 'SEA',
  SEA: 'SEA',
  'St. Louis Blues': 'STL',
  STL: 'STL',
  'Tampa Bay Lightning': 'TBL',
  TBL: 'TBL',
  'Toronto Maple Leafs': 'TOR',
  TOR: 'TOR',
  'Vancouver Canucks': 'VAN',
  VAN: 'VAN',
  'Vegas Golden Knights': 'VGK',
  VGK: 'VGK',
  'Washington Capitals': 'WSH',
  WSH: 'WSH',
  'Winnipeg Jets': 'WPG',
  WPG: 'WPG',
}
export const divisions = ['Atlantic', 'Central', 'Metropolitan', 'Pacific']
